### ISSUE TITLE
Keyboard shortcuts for opening wingpanel's slingshot app launcher don't work

### ISSUE THREAD

**Issue by nekohayo** [decathorpe/elementary-stable-rpms#4] opened 2016-11-26 02:58 UTC
I tried the Super/Win key, alt+F1, alt+F2, Super+S, nothing works, even if I set a custom shortcut in the preferences.

Setting a hotcorner action to open the launcher menu thingy doesn't work either, so I'm presuming this is a packaging issue rather than an upstream issue...

**Comment by decathorpe** [comment] 2016-11-26 23:06
I am aware of this issue (it has been annoying me for some time already).
I will try to get an upstream developer to help me with troubleshooting.

**Comment by ziflex** [comment] 2017-06-22 13:03
There are more shortcuts which don't work.
Even custom bindings don't work.

**Comment by ziflex** [comment] 2017-06-22 13:04
Any updates on this, btw?

**Comment by davidmhewitt** [comment] 2017-06-23 09:21
@decathorpe I've just copied this from Slack in case you miss it:

> David Hewitt [9:59 AM] 
> ```
> [org.pantheon.desktop.gala.behavior]
> panel-main-menu-action='wingpanel --toggle-indicator=app-launcher'
> ```

You'll need to check the above key is set as shown in dconf. Apologies if that's already set, but the symptoms sound familiar to that key not being set.

**Comment by decathorpe** [comment] 2017-06-24 10:18
Yes, that key isn't set by default in the gala gsettings file ...

What would be the best approach to fix this, @davidmhewitt ?

I think the easiest (and least invasive) solution would be to patch the gala gsettings schema to supply this value as a default value (I am wondering why that isn't the case already) ...

**Comment by davidmhewitt** [comment] 2017-06-24 10:20
@decathorpe Why it's not set as a default value for gala, I don't know. Sounds like another question for the slack channel.

Glad I was able to assist you in finding the cause of the issue, however.

**Comment by ziflex** [comment] 2017-07-26 15:00
How can I fix bindings for ``fn`` buttons? Like for volume control? Basically, none of hot keys is working.

**Comment by decathorpe** [comment] 2017-07-26 21:25
@ziflex I don't know what's going wrong there, but all media keys on my keyboard work as expected.
Did you use switchboard to set the keybindings? Does it work if you use gnome-control-center?

**Comment by ziflex** [comment] 2017-07-27 15:59
@decathorpe before I switched to Pantheon, everything had worked fine. But now, all key bindings just do not work, even though they are configured via ``Keyboard`` app in both Pantheon settings and Gnome settings. Even custom bindings do not work.
I have a suspicion that all these keys events are ignored and not handled properly.

**Comment by decathorpe** [comment] 2017-07-27 17:10
@ziflex Can you check if the "gsd-keyboard" and "gsd-media-keys" processes are running in your session?

**Comment by ziflex** [comment] 2017-07-27 19:21
@decathorpe I'm on F25. Yes, ``gnome-settings-daemon`` is running.

**Comment by codecowboy** [comment] 2017-08-03 10:28
I'm also seeing this issue. Mac extended keyboard. I can get the applications menu by using Ctrl-Alt+Space but would like to change it. https://elementaryos.stackexchange.com/questions/12910/keyboard-shortcut-for-application-chooser

**Comment by decathorpe** [comment] 2017-08-03 18:30
I can't debug what's going wrong because I can't reproduce the error on my systems.

You'll have to give me more information than "it doesn't work" before I can do anything productive.

**Comment by decathorpe** [comment] 2018-07-12 14:13
With the latest updates to `gala`, `pantheon-session-settings` and friends, this issue should be resolved (Alt-F1 should open the application menu). I'm going to close this issue since this fixes the original problem.

**Closed by decathorpe** 2018-07-12 14:13 UTC
Labels: bug, help wanted
